print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/lanedator/Documents/unity/Racer/Assets/3D_Assets/RacerBil.mb"`)
{		
	file -o "/Users/lanedator/Documents/unity/Racer/Assets/3D_Assets/RacerBil.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/lanedator/Documents/unity/Racer/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/lanedator/Documents/unity/Racer/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/lanedator/Documents/unity/Racer/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
